# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
   adapter: mysql2
   database: rails_api_demo
   username: root
   password: lkgukg
   host: localhost

test:
   adapter: mysql2
   database: rails_api_demo_test
   username: root
   password: lkgukg
   host: localhost

production:
   adapter: mysql2
   database:
   username:
   password:
   host:

